# Generated by Django 4.1.7 on 2023-04-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
