# Generated by Django 4.1.7 on 2023-04-13 22:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_profile_picture_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_link',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='', unique=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='project_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='static/img/extras/person.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
