# Generated by Django 4.1.7 on 2023-04-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_photo_photo_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='logo_link',
        ),
        migrations.AddField(
            model_name='project',
            name='logo_img',
            field=models.ImageField(default='static/img/extras/noImg.jpeg', null=True, upload_to=''),
        ),
    ]
