# Generated by Django 4.1.7 on 2023-04-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_project_logo_link_project_logo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo_img',
            field=models.ImageField(default='noImg.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='person.png', null=True, upload_to=''),
        ),
    ]
